# Generated by Django 6.0.3 on 2026-03-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='notes',
            new_name='payment_number',
        ),
        migrations.AddField(
            model_name='registration',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_transaction',
            field=models.TextField(blank=True),
        ),
    ]
